CREATE DATABASE PROVA_POO_DB;

USE PROVA_POO_DB;

CREATE TABLE GAMES(

ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
PRODUTORA VARCHAR(80) NOT NULL,
PRECO FLOAT NOT NULL,

PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE USUARIO(

ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(12) NOT NULL,

PRIMARY KEY (ID)
)ENGINE=INNODB;